import Foundation

/// The whole capture decision, with no `NSPasteboard` dependency so it can be
/// tested directly. `ClipboardMonitor` supplies the inputs and holds no policy.
enum ClipboardCapture {

    struct Candidate: Equatable {
        let code: String
        let language: SupportedLanguage
    }

    /// Pasteboard markers meaning "do not record this".
    ///
    /// Password managers set `ConcealedType`; `TransientType` marks values not
    /// meant to persist; `AutoGeneratedType` marks machine-produced content.
    /// Honouring all three is what keeps a password out of a capture prompt.
    static let excludedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    /// Stages run cheapest-rejection-first.
    static func candidate(text: String?, types: Set<String>, isOwnWrite: Bool) -> Candidate? {
        guard !isOwnWrite else { return nil }
        guard types.isDisjoint(with: excludedTypes) else { return nil }
        guard let text, CodeShapeHeuristics.isLikelyCode(text) else { return nil }

        let language = LanguageDetector.detect(code: text)
        guard language != .unknown else { return nil }

        return Candidate(code: text, language: language)
    }
}
