import XCTest
@testable import Snippets

/// The capture decision, tested without ever touching a real pasteboard.
final class ClipboardCaptureTests: XCTestCase {

    private let code = """
    func parse(_ input: String) -> Int {
        return input.count
    }
    """

    func test_plainCodeCopiedElsewhere_isCaptured() {
        let candidate = ClipboardCapture.candidate(text: code, types: [], isOwnWrite: false)
        XCTAssertEqual(candidate?.code, code)
        XCTAssertEqual(candidate?.language, .swift)
    }

    // MARK: Rejections

    /// Copying from our own panel writes to the same pasteboard we watch.
    /// Without this the app would prompt the user to save a snippet they
    /// just copied out of it.
    func test_ownWrite_isRejected() {
        XCTAssertNil(ClipboardCapture.candidate(text: code, types: [], isOwnWrite: true))
    }

    func test_concealedType_isRejected() {
        XCTAssertNil(ClipboardCapture.candidate(
            text: code, types: ["org.nspasteboard.ConcealedType"], isOwnWrite: false
        ))
    }

    func test_transientType_isRejected() {
        XCTAssertNil(ClipboardCapture.candidate(
            text: code, types: ["org.nspasteboard.TransientType"], isOwnWrite: false
        ))
    }

    func test_autoGeneratedType_isRejected() {
        XCTAssertNil(ClipboardCapture.candidate(
            text: code, types: ["org.nspasteboard.AutoGeneratedType"], isOwnWrite: false
        ))
    }

    func test_excludedTypeAlongsideOrdinaryTypes_isStillRejected() {
        XCTAssertNil(ClipboardCapture.candidate(
            text: code,
            types: ["public.utf8-plain-text", "org.nspasteboard.ConcealedType"],
            isOwnWrite: false
        ))
    }

    func test_prose_isRejected() {
        XCTAssertNil(ClipboardCapture.candidate(
            text: "The quick brown fox jumps over the lazy dog and keeps running.",
            types: [], isOwnWrite: false
        ))
    }

    func test_nilText_isRejected() {
        XCTAssertNil(ClipboardCapture.candidate(text: nil, types: [], isOwnWrite: false))
    }

    func test_ordinaryTypesAreNotExcluded() {
        XCTAssertNotNil(ClipboardCapture.candidate(
            text: code, types: ["public.utf8-plain-text"], isOwnWrite: false
        ))
    }
}
